apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml
- ingress.yaml
images:
- name: quay.io/argocicd/hello-world
  newName: quay.io/argocicd/hello-world
  newTag: ver_f284dc
